#!/usr/bin/env node
// Design tokens from DESIGN.md front matter (plan KTD1).
//
// Reads the `colors` (light + dark), `spacing`, `rounded` and `motion`
// blocks and writes:
//   assets/brand/tokens.css   custom properties, light in :root, dark under
//                             prefers-color-scheme
//   assets/brand/tokens.json  DTCG-shaped (hex canonical, OKLCH alongside)
//   assets/brand/ansi.json    text roles and statuses mapped to ANSI-16 slots
//
// Hex stays canonical because DESIGN.md section 6.1 measured contrast in hex.
// The outputs are committed; tests/unit/tokens.test.ts fails when they drift.
//
// Usage: node scripts/build-tokens.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

export const OUTPUT_FILES = ['assets/brand/tokens.css', 'assets/brand/tokens.json', 'assets/brand/ansi.json']

const THEMES = ['light', 'dark']
const HEADER = 'Generated by scripts/build-tokens.mjs from DESIGN.md front matter. Do not edit by hand.'

/**
 * Parse the token blocks out of DESIGN.md's YAML front matter. Only the
 * subset DESIGN.md uses is understood; anything unexpected inside a token
 * block throws rather than being guessed at.
 */
export function parseFrontMatter(markdown) {
  const match = /^---\n([\s\S]*?)\n---\n/.exec(markdown)
  if (!match) throw new Error('DESIGN.md: no YAML front matter found')
  const lines = match[1].split('\n')

  const colors = {}
  let spacing
  let rounded
  const motion = {}
  let block
  let theme

  for (const [i, line] of lines.entries()) {
    const where = `DESIGN.md front matter line ${i + 2}`
    if (line.trim() === '' || line.trimStart().startsWith('#')) continue

    const top = /^([a-z][\w-]*):\s*(.*)$/.exec(line)
    if (top) {
      block = top[1]
      theme = undefined
      const inline = top[2].trim()
      if (block === 'spacing') spacing = parseFlowSeq(inline, where)
      else if (block === 'rounded') rounded = parseFlowMap(inline, where)
      else if ((block === 'colors' || block === 'motion') && inline !== '') {
        throw new Error(`${where}: expected a nested block under "${block}"`)
      }
      continue
    }

    if (block === 'colors') {
      const t = /^ {2}([a-z]+):\s*$/.exec(line)
      if (t) {
        theme = t[1]
        if (!THEMES.includes(theme)) throw new Error(`${where}: unknown color theme "${theme}"`)
        if (colors[theme]) throw new Error(`${where}: duplicate color theme "${theme}"`)
        colors[theme] = {}
        continue
      }
      const c = /^ {4}([a-z][a-z0-9-]*):\s*"(#[0-9A-Fa-f]{6})"\s*$/.exec(line)
      if (c && theme) {
        if (c[1] in colors[theme]) throw new Error(`${where}: duplicate color "${theme}.${c[1]}"`)
        colors[theme][c[1]] = c[2].toUpperCase()
        continue
      }
      throw new Error(`${where}: unrecognized line in colors: ${JSON.stringify(line)}`)
    }

    if (block === 'motion') {
      const m = /^ {2}([a-z][\w-]*):\s*(.+)$/.exec(line)
      if (!m) throw new Error(`${where}: unrecognized line in motion: ${JSON.stringify(line)}`)
      motion[m[1]] = unquote(m[2].trim())
      continue
    }
    // Indented lines of any other block (description, typography) are not tokens.
  }

  for (const t of THEMES) if (!colors[t]) throw new Error(`DESIGN.md: colors.${t} is missing`)
  if (!spacing) throw new Error('DESIGN.md: spacing is missing')
  if (!rounded) throw new Error('DESIGN.md: rounded is missing')
  if (Object.keys(motion).length === 0) throw new Error('DESIGN.md: motion is missing')
  return { colors, spacing, rounded, motion }
}

function unquote(s) {
  const q = /^"(.*)"$/.exec(s)
  return q ? q[1] : s
}

function parseScalar(raw, where) {
  const s = raw.trim()
  if (/^-?\d+(\.\d+)?$/.test(s)) return Number(s)
  if (/^".*"$/.test(s)) return s.slice(1, -1)
  throw new Error(`${where}: unsupported value ${JSON.stringify(s)}`)
}

function splitFlow(body) {
  const parts = []
  let cur = ''
  let quoted = false
  for (const ch of body) {
    if (ch === '"') quoted = !quoted
    if (ch === ',' && !quoted) {
      parts.push(cur)
      cur = ''
    } else cur += ch
  }
  if (cur.trim() !== '') parts.push(cur)
  return parts
}

function parseFlowSeq(inline, where) {
  const m = /^\[(.*)\]$/.exec(inline)
  if (!m) throw new Error(`${where}: expected a [flow, sequence]`)
  return splitFlow(m[1]).map((p) => parseScalar(p, where))
}

function parseFlowMap(inline, where) {
  const m = /^\{(.*)\}$/.exec(inline)
  if (!m) throw new Error(`${where}: expected a { flow: map }`)
  const out = {}
  for (const part of splitFlow(m[1])) {
    const kv = /^\s*([a-z][\w-]*):\s*(.+)$/.exec(part)
    if (!kv) throw new Error(`${where}: bad map entry ${JSON.stringify(part)}`)
    out[kv[1]] = parseScalar(kv[2], where)
  }
  return out
}

/** Throws, naming the missing keys, when the two themes define different tokens. */
export function assertSameColorKeys(colors) {
  const [a, b] = THEMES
  const missing = (from, to) => Object.keys(colors[from]).filter((k) => !(k in colors[to]))
  const problems = []
  const missB = missing(a, b)
  const missA = missing(b, a)
  if (missB.length) problems.push(`${b} is missing: ${missB.join(', ')}`)
  if (missA.length) problems.push(`${a} is missing: ${missA.join(', ')}`)
  if (problems.length) {
    throw new Error(`DESIGN.md colors: light and dark must define the same keys; ${problems.join('; ')}`)
  }
}

// --- color math -----------------------------------------------------------

export function hexToRgb(hex) {
  const n = Number.parseInt(hex.slice(1), 16)
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((v) => v / 255)
}

export function srgbToLinear(c) {
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
}

function fmt(n, digits) {
  const v = Number(n.toFixed(digits))
  return String(Object.is(v, -0) ? 0 : v)
}

/** sRGB hex to an OKLCH CSS string (Ottosson's OKLab matrices). */
export function hexToOklch(hex) {
  const [r, g, b] = hexToRgb(hex).map(srgbToLinear)
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s
  const C = Math.hypot(A, B)
  let H = 0
  if (Number(C.toFixed(4)) !== 0) {
    H = (Math.atan2(B, A) * 180) / Math.PI
    if (H < 0) H += 360
    if (Number(H.toFixed(2)) === 360) H = 0
  }
  return `oklch(${fmt(L, 4)} ${fmt(C, 4)} ${fmt(H, 2)})`
}

// --- outputs --------------------------------------------------------------

function parseDuration(value, key) {
  const m = /^(\d+)ms$/.exec(value)
  if (!m) throw new Error(`DESIGN.md motion.${key}: expected a duration like 180ms, got ${JSON.stringify(value)}`)
  return Number(m[1])
}

function parseCubicBezier(value, key) {
  const m = /^cubic-bezier\(([^)]*)\)$/.exec(value)
  const nums = m ? m[1].split(',').map((p) => Number(p.trim())) : []
  if (nums.length !== 4 || nums.some((n) => !Number.isFinite(n))) {
    throw new Error(`DESIGN.md motion.${key}: expected cubic-bezier(a, b, c, d), got ${JSON.stringify(value)}`)
  }
  return nums
}

function parseRadius(value, key) {
  if (typeof value === 'number') return { px: value }
  const m = /^(\d+%)\s*(?:\((.*)\))?$/.exec(value)
  if (!m) throw new Error(`DESIGN.md rounded.${key}: unsupported value ${JSON.stringify(value)}`)
  return { css: m[1], description: m[2] }
}

function motionTokens(motion) {
  return Object.entries(motion).map(([key, value]) =>
    key.startsWith('ease')
      ? { key, kind: 'easing', bezier: parseCubicBezier(value, key) }
      : { key, kind: 'duration', ms: parseDuration(value, key) },
  )
}

function renderCss(fm) {
  const colorLines = (theme, indent) =>
    Object.entries(fm.colors[theme]).map(
      ([k, hex]) => `${indent}--argus-color-${k}: ${hex}; /* ${hexToOklch(hex)} */`,
    )
  const out = [`/* ${HEADER} */`, '', ':root {', ...colorLines('light', '  ')]
  out.push('')
  for (const n of fm.spacing) out.push(`  --argus-space-${n}: ${n}px;`)
  out.push('')
  for (const [k, v] of Object.entries(fm.rounded)) {
    const r = parseRadius(v, k)
    out.push(`  --argus-radius-${k}: ${r.css ?? `${r.px}px`};`)
  }
  out.push('')
  for (const t of motionTokens(fm.motion)) {
    out.push(
      t.kind === 'duration'
        ? `  --argus-motion-${t.key}: ${t.ms}ms;`
        : `  --argus-motion-${t.key}: cubic-bezier(${t.bezier.join(', ')});`,
    )
  }
  out.push('}', '', '@media (prefers-color-scheme: dark) {', '  :root {', ...colorLines('dark', '    '), '  }', '}', '')
  return out.join('\n')
}

function renderJson(fm) {
  const color = {}
  for (const theme of THEMES) {
    color[theme] = {}
    for (const [k, hex] of Object.entries(fm.colors[theme])) {
      color[theme][k] = {
        $type: 'color',
        $value: {
          colorSpace: 'srgb',
          components: hexToRgb(hex).map((c) => Number(c.toFixed(4))),
          hex,
        },
        $extensions: { 'argus.oklch': hexToOklch(hex) },
      }
    }
  }
  const spacing = {}
  for (const n of fm.spacing) spacing[String(n)] = { $type: 'dimension', $value: { value: n, unit: 'px' } }
  const radius = {}
  for (const [k, v] of Object.entries(fm.rounded)) {
    const r = parseRadius(v, k)
    radius[k] =
      r.px !== undefined
        ? { $type: 'dimension', $value: { value: r.px, unit: 'px' } }
        : { $value: r.css, ...(r.description ? { $description: r.description } : {}) }
  }
  const motion = {}
  for (const t of motionTokens(fm.motion)) {
    motion[t.key] =
      t.kind === 'duration'
        ? { $type: 'duration', $value: { value: t.ms, unit: 'ms' } }
        : { $type: 'cubicBezier', $value: t.bezier }
  }
  return `${JSON.stringify({ $description: HEADER, color, spacing, radius, motion }, null, 2)}\n`
}

// Section 6.1: the terminal palette maps to ANSI-16 slots so the user's
// terminal theme stays in charge; truecolor hexes ride along for --color=brand.
const ANSI_ROLES = {
  ink: { slot: 'default', sgr: '39' },
  'ink-2': { slot: 'default', sgr: '39' },
  'ink-3': { slot: 'dim', sgr: '2' },
  accent: { slot: 'blue', sgr: '34' },
  passed: { slot: 'green', sgr: '32' },
  failed: { slot: 'red', sgr: '31' },
  caution: { slot: 'yellow', sgr: '33' },
}

// Section 6.1 status table, "Terminal fallback" column. Glyphs live in
// src/report/viewmodel.ts (STATUS_GLYPH), not here.
const ANSI_STATUS = {
  passed: { role: 'passed', sgr: '32' },
  failed: { role: 'failed', sgr: '31' },
  inconclusive: { role: 'caution', sgr: '33' },
  blocked: { role: 'ink', sgr: '1' },
  unavailable: { role: 'ink-3', sgr: '2' },
  skipped: { role: 'ink-3', sgr: '2' },
}

function renderAnsi(fm) {
  const roles = {}
  for (const [role, map] of Object.entries(ANSI_ROLES)) {
    for (const t of THEMES) {
      if (!(role in fm.colors[t])) throw new Error(`ansi.json: role "${role}" has no ${t} color in DESIGN.md`)
    }
    roles[role] = { ...map, light: fm.colors.light[role], dark: fm.colors.dark[role] }
  }
  return `${JSON.stringify({ $description: HEADER, roles, status: ANSI_STATUS }, null, 2)}\n`
}

/** Render every output from DESIGN.md text; keys are repo-relative paths. */
export function buildTokens(markdown) {
  const fm = parseFrontMatter(markdown)
  assertSameColorKeys(fm.colors)
  return {
    'assets/brand/tokens.css': renderCss(fm),
    'assets/brand/tokens.json': renderJson(fm),
    'assets/brand/ansi.json': renderAnsi(fm),
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const outputs = buildTokens(readFileSync(join(ROOT, 'DESIGN.md'), 'utf8'))
  for (const [file, text] of Object.entries(outputs)) {
    mkdirSync(dirname(join(ROOT, file)), { recursive: true })
    writeFileSync(join(ROOT, file), text)
    console.log(`wrote ${file}`)
  }
}
